In [49]:
from pathlib import Path
import sys

import numpy as np
import pandas as pd

CWD = Path.cwd()
AI_MODULE_DIR = CWD if (CWD / "main.ipynb").exists() else CWD / "ai_module"
PROJECT_ROOT = AI_MODULE_DIR.parent
sys.path.insert(0, str(AI_MODULE_DIR.resolve()))
sys.path.insert(0, str(PROJECT_ROOT.resolve()))

from backend.notebook_training import (
    FINAL_MODEL_CONFIGS,
    FINAL_MODEL_DATASET_IDS,
    train_or_reuse_final_models,
)

from backend.registry import register_dataset, DATASETS_DIR, load_dataset
from feature_groups import build_feature_datasets

In [50]:
df = pd.read_csv('brfss_2024.zip', compression='zip')
pd.set_option('display.max_columns', None)

target_col = 'CVDSTRK3'

# Keep only rows where we have a clear stroke status
df = df[(df[target_col] == 1) | (df[target_col] == 2)]

# Recode BRFSS survey values (1=Yes, 2=No) to standard binary (1=Stroke, 0=No Stroke)
df[target_col] = (df[target_col] == 1).astype(int)

print("Amount of rows and features:", df.shape)
df.head(1)

Amount of rows and features: (456218, 301)

,_STATE,FMONTH,IDATE,IMONTH,IDAY,IYEAR,DISPCODE,SEQNO,_PSU,CTELENM1,PVTRESD1,COLGHOUS,STATERE1,CELPHON1,LADULT1,NUMADULT,RESPSLC1,LANDSEX3,SAFETIME,CTELNUM1,CELLFON5,CADULT1,CELLSEX3,PVTRESD3,CCLGHOUS,CSTATE1,LANDLINE,HHADULT,SEXVAR,GENHLTH,PHYSHLTH,MENTHLTH,POORHLTH,PRIMINS2,PERSDOC3,MEDCOST1,CHECKUP1,EXERANY2,LASTDEN4,RMVTETH4,CVDINFR4,CVDCRHD4,CVDSTRK3,ASTHMA3,ASTHNOW,CHCSCNC1,CHCOCNC1,CHCCOPD3,ADDEPEV3,CHCKDNY2,HAVARTH4,DIABETE4,DIABAGE4,MARITAL,EDUCA,RENTHOM1,NUMHHOL4,NUMPHON4,CPDEMO1C,VETERAN3,EMPLOY1,CHILDREN,INCOME3,PREGNANT,WEIGHT2,HEIGHT3,DEAF,BLIND,DECIDE,DIFFWALK,DIFFDRES,DIFFALON,HADMAM,HOWLONG,CERVSCRN,CRVCLCNC,CRVCLPAP,CRVCLHPV,HADHYST2,HADSIGM4,COLNSIGM,COLNTES1,SIGMTES1,LASTSIG4,COLNCNCR,VIRCOLO1,VCLNTES2,SMALSTOL,STOLTEST,STOOLDN2,BLDSTFIT,SDNATES1,SMOKE100,SMOKDAY2,USENOW3,ECIGNOW3,LCSFIRST,LCSNUMCG,LCSCTSC1,LCSSCNCR,LCSCTWHN,ALCDAY4,AVEDRNK4,DRNK3GE5,MAXDRNKS,FLUSHOT7,FLSHTMY3,IMFVPLA5,PNEUVAC4,HIVTST7,HIVTSTD3,HIVRISK5,PDIABTS1,PREDIAB2,DIABTYPE,INSULIN1,CHKHEMO3,EYEEXAM1,DIABEYE1,DIABEDU1,FEETSORE,ARTHEXER,SHINGLE2,HPVADVC4,HPVADSH1,TETANUS1,CNCRDIFF,CNCRAGE,CNCRTYP2,CSRVTRT3,CSRVDOC1,CSRVSUM,CSRVRTRN,CSRVINST,CSRVINSR,CSRVDEIN,CSRVCLIN,CSRVPAIN,CSRVCTL2,PSATEST1,PSATIME1,PCPSARS2,PSASUGS1,PCSTALK2,CIMEMLO1,CDWORRY,CDDISCU1,CDHOUS1,CDSOCIA1,CAREGIV1,CRGVREL5,CRGVPRB4,CRGVALZD,CRGVNURS,CRGVPER2,CRGVHOU2,CRGVHRS2,CRGVLNG2,ACEDEPRS,ACEDRINK,ACEDRUGS,ACEPRISN,ACEDIVRC,ACEPUNCH,ACEHURT1,ACESWEAR,ACETOUCH,ACETTHEM,ACEHVSEX,ACEADSAF,ACEADNED,LSATISFY,EMTSUPRT,SDLONELY,SDHEMPLY,FOODSTMP,SDHFOOD1,SDHBILLS,SDHUTILS,SDHTRNSP,HOWSAFE1,MARIJAN1,MARJSMOK,MARJEAT,MARJVAPE,MARJDAB,MARJOTHR,USEMRJN4,LASTSMK2,STOPSMK2,MENTCIGS,MENTECIG,HEATTBCO,SSBSUGR2,SSBFRUT3,FIREARM5,GUNLOAD,LOADULK2,RCSGEND1,RCSXBRTH,RCSRLTN2,CASTHDX2,CASTHNO2,SOMALE,SOFEMALE,HADSEX,PFPPRVN4,TYPCNTR9,NOBCUSE8,QSTVER,QSTLANG,HPVDSHT,ICFQSTVR,_METSTAT,_URBSTAT,MSCODE,_STSTR,_STRWT,_RAWRAKE,_WT2RAKE,_IMPRACE,_CHISPNC,_CRACE1,CAGEG,_CLLCPWT,_DUALUSE,_DUALCOR,_LLCPWT2,_LLCPWT,_RFHLTH,_PHYS14D,_MENT14D,_HLTHPL2,_HCVU654,_TOTINDA,_EXTETH3,_ALTETH3,_DENVST3,_MICHD,_LTASTH1,_CASTHM1,_ASTHMS1,_DRDXAR2,_MRACE1,_HISPANC,_RACE,_RACEG21,_RACEGR3,_RACEPRV,_SEX,_AGEG5YR,_AGE65YR,_AGE80,_AGE_G,HTIN4,HTM4,WTKG3,_BMI5,_BMI5CAT,_RFBMI5,_CHLDCNT,_EDUCAG,_INCOMG1,_RFMAM23,_MAM402Y,_CRVSCRN,_RFPAP37,_HPV5YR1,_PAPHPV1,_HADCOLN,_CLNSCP2,_HADSIGM,_SGMSCP2,_SGMS102,_RFBLDS6,_STOLDN2,_VIRCOL2,_SBONTI2,_CRCREC3,_SMOKER3,_RFSMOK3,_CURECI3,LCSLAST_,LCSNUMC_,_LCSAGE,_LCSYSMK,_PACKDAY,_PACKYRS,_LCSYQTS,_LCSSMKG,_LCSELIG,_LCSCTSN,_LCSPSTF,DRNKANY6,DROCDY4_,_RFBING6,_DRNKWK3,_RFDRHV9,_FLSHOT7,_PNEUMO3,_AIDTST4
0,1.0,2.0,2282024,2.0,28.0,2024,1100.0,2024000001,2.024000e+09,1.0,1.0,NaN,1.0,2.0,1.0,1.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,3.0,2.0,88.0,88.0,3.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,0,2.0,NaN,1.0,2.0,2.0,2.0,2.0,1.0,3.0,NaN,3.0,4.0,1.0,2.0,NaN,1.0,2.0,7.0,88.0,99.0,NaN,131.0,504.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,1.0,2.0,1.0,2.0,1.0,1.0,1.0,3.0,NaN,NaN,1.0,1.0,7.0,1.0,7.0,2.0,NaN,NaN,2.0,NaN,3.0,1.0,NaN,NaN,1.0,7.0,NaN,888.0,NaN,NaN,NaN,1.0,777777.0,1.0,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,5.0,2.0,2.0,5.0,2.0,2.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,10.0,1.0,NaN,NaN,1.0,1.0,1.0,11011.0,28.393219,1.0,28.393219,1.0,NaN,NaN,NaN,NaN,1.0,0.465294,220.149005,261.525511,1.0,2.0,1.0,1.0,9.0,1.0,2.0,1.0,1.0,2.0,1.0,1.0,3.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,12.0,2.0,78.0,6.0,64.0,163.0,5942.0,2249.0,2.0,1.0,1.0,2.0,9.0,1.0,NaN,1.0,NaN,NaN,NaN,1.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,1.0,1.0,NaN,NaN,2.0,NaN,NaN,NaN,NaN,6.0,2.0,NaN,9.0,2.0,5.397605e-79,1.0,5.397605e-79,1.0,1.0,2.0,2.0

In [51]:
# Manual feature selection - the goal is to drop features such as administrative and survey design variables.
# These variables tell how the data was collected, not what respondents reported about their health or behaviour.

df.drop(columns=[
    # When the survey was conducted and general identifiers whether is eligible to be included in the survey
    "FMONTH", "IDATE", "IMONTH", "IDAY", "IYEAR", "DISPCODE", "SEQNO", "_PSU", "SAFETIME",
    "LADULT1", "CADULT1", "RESPSLC1", "CTELENM1", "CTELNUM1","CELPHON1", "CELLFON5", "LANDLINE",
    "LANDSEX3", "CELLSEX3",
    
    # Residency and household variables
    "PVTRESD1", "PVTRESD3", "COLGHOUS", "STATERE1", "CSTATE1", "NUMADULT", 
    "HHADULT", "NUMHHOL4", "NUMPHON4", "CPDEMO1C", "CCLGHOUS", "GUNLOAD", 
    "LOADULK2", "FIREARM5", "_CHLDCNT", "CHILDREN", "CAGEG", "RENTHOM1",

    # Survey language and version variables
    "QSTVER", "QSTLANG", "ICFQSTVR",

    # Statistical sampling weights & design variables
    "_STSTR", "_STRWT", "_RAWRAKE", "_WT2RAKE", "_CLLCPWT", 
    "_DUALUSE", "_DUALCOR", "_LLCPWT2", "_LLCPWT",

    # Post Course of Treatment questions
    "CSRVINST", "CSRVINSR", "CSRVDEIN", "PCSTALK2", "CSRVSUM",

    # Caregiver - about the respondent's relationship to their caregiver, 
    # not about the respondent's health or behaviour.
    "CAREGIV1", "CRGVREL5", "CRGVPRB4", "CRGVALZD", 
    "CRGVNURS", "CRGVPER2", "CRGVHOU2", "CRGVHRS2", "CRGVLNG2", 

    # Family Planning
    "RCSRLTN2", "HADSEX", "PFPPRVN4", "TYPCNTR9", "NOBCUSE8",

    "RCSXBRTH", "RCSGEND1", "HPVDSHT", "CSRVCTL2",
], inplace=True)

print("Dataset after dropping columns that are unrelated to health outcomes by design:", df.shape)
df.head(1)

Dataset after dropping columns that are unrelated to health outcomes by design: (456218, 229)

,_STATE,SEXVAR,GENHLTH,PHYSHLTH,MENTHLTH,POORHLTH,PRIMINS2,PERSDOC3,MEDCOST1,CHECKUP1,EXERANY2,LASTDEN4,RMVTETH4,CVDINFR4,CVDCRHD4,CVDSTRK3,ASTHMA3,ASTHNOW,CHCSCNC1,CHCOCNC1,CHCCOPD3,ADDEPEV3,CHCKDNY2,HAVARTH4,DIABETE4,DIABAGE4,MARITAL,EDUCA,VETERAN3,EMPLOY1,INCOME3,PREGNANT,WEIGHT2,HEIGHT3,DEAF,BLIND,DECIDE,DIFFWALK,DIFFDRES,DIFFALON,HADMAM,HOWLONG,CERVSCRN,CRVCLCNC,CRVCLPAP,CRVCLHPV,HADHYST2,HADSIGM4,COLNSIGM,COLNTES1,SIGMTES1,LASTSIG4,COLNCNCR,VIRCOLO1,VCLNTES2,SMALSTOL,STOLTEST,STOOLDN2,BLDSTFIT,SDNATES1,SMOKE100,SMOKDAY2,USENOW3,ECIGNOW3,LCSFIRST,LCSNUMCG,LCSCTSC1,LCSSCNCR,LCSCTWHN,ALCDAY4,AVEDRNK4,DRNK3GE5,MAXDRNKS,FLUSHOT7,FLSHTMY3,IMFVPLA5,PNEUVAC4,HIVTST7,HIVTSTD3,HIVRISK5,PDIABTS1,PREDIAB2,DIABTYPE,INSULIN1,CHKHEMO3,EYEEXAM1,DIABEYE1,DIABEDU1,FEETSORE,ARTHEXER,SHINGLE2,HPVADVC4,HPVADSH1,TETANUS1,CNCRDIFF,CNCRAGE,CNCRTYP2,CSRVTRT3,CSRVDOC1,CSRVRTRN,CSRVCLIN,CSRVPAIN,PSATEST1,PSATIME1,PCPSARS2,PSASUGS1,CIMEMLO1,CDWORRY,CDDISCU1,CDHOUS1,CDSOCIA1,ACEDEPRS,ACEDRINK,ACEDRUGS,ACEPRISN,ACEDIVRC,ACEPUNCH,ACEHURT1,ACESWEAR,ACETOUCH,ACETTHEM,ACEHVSEX,ACEADSAF,ACEADNED,LSATISFY,EMTSUPRT,SDLONELY,SDHEMPLY,FOODSTMP,SDHFOOD1,SDHBILLS,SDHUTILS,SDHTRNSP,HOWSAFE1,MARIJAN1,MARJSMOK,MARJEAT,MARJVAPE,MARJDAB,MARJOTHR,USEMRJN4,LASTSMK2,STOPSMK2,MENTCIGS,MENTECIG,HEATTBCO,SSBSUGR2,SSBFRUT3,CASTHDX2,CASTHNO2,SOMALE,SOFEMALE,_METSTAT,_URBSTAT,MSCODE,_IMPRACE,_CHISPNC,_CRACE1,_RFHLTH,_PHYS14D,_MENT14D,_HLTHPL2,_HCVU654,_TOTINDA,_EXTETH3,_ALTETH3,_DENVST3,_MICHD,_LTASTH1,_CASTHM1,_ASTHMS1,_DRDXAR2,_MRACE1,_HISPANC,_RACE,_RACEG21,_RACEGR3,_RACEPRV,_SEX,_AGEG5YR,_AGE65YR,_AGE80,_AGE_G,HTIN4,HTM4,WTKG3,_BMI5,_BMI5CAT,_RFBMI5,_EDUCAG,_INCOMG1,_RFMAM23,_MAM402Y,_CRVSCRN,_RFPAP37,_HPV5YR1,_PAPHPV1,_HADCOLN,_CLNSCP2,_HADSIGM,_SGMSCP2,_SGMS102,_RFBLDS6,_STOLDN2,_VIRCOL2,_SBONTI2,_CRCREC3,_SMOKER3,_RFSMOK3,_CURECI3,LCSLAST_,LCSNUMC_,_LCSAGE,_LCSYSMK,_PACKDAY,_PACKYRS,_LCSYQTS,_LCSSMKG,_LCSELIG,_LCSCTSN,_LCSPSTF,DRNKANY6,DROCDY4_,_RFBING6,_DRNKWK3,_RFDRHV9,_FLSHOT7,_PNEUMO3,_AIDTST4
0,1.0,2.0,3.0,2.0,88.0,88.0,3.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,0,2.0,NaN,1.0,2.0,2.0,2.0,2.0,1.0,3.0,NaN,3.0,4.0,2.0,7.0,99.0,NaN,131.0,504.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,1.0,2.0,1.0,2.0,1.0,1.0,1.0,3.0,NaN,NaN,1.0,1.0,7.0,1.0,7.0,2.0,NaN,NaN,2.0,NaN,3.0,1.0,NaN,NaN,1.0,7.0,NaN,888.0,NaN,NaN,NaN,1.0,777777.0,1.0,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,5.0,2.0,2.0,5.0,2.0,2.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,2.0,1.0,1.0,1.0,1.0,NaN,NaN,1.0,2.0,1.0,1.0,9.0,1.0,2.0,1.0,1.0,2.0,1.0,1.0,3.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,12.0,2.0,78.0,6.0,64.0,163.0,5942.0,2249.0,2.0,1.0,2.0,9.0,1.0,NaN,1.0,NaN,NaN,NaN,1.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,1.0,1.0,NaN,NaN,2.0,NaN,NaN,NaN,NaN,6.0,2.0,NaN,9.0,2.0,5.397605e-79,1.0,5.397605e-79,1.0,1.0,2.0,2.0

In [52]:
# Find highly correlated features using Cramér's V for categorical variables.

# pairs_df = find_high_correlation_pairs(df, threshold=0.85, sample_n = 50_000, random_state = 42)
# print(pairs_df.to_string(index=False))

In [53]:
# Remove redundant features

df.drop(columns=[
    # General health / days unhealthy
    # Keep: GENHLTH, PHYSHLTH, MENTHLTH, _TOTINDA 
    # Precise amount of days unhealthy in the past 30 days, while the alternatives are coarser categories or binary variables
    "_RFHLTH", "_PHYS14D", "_MENT14D", "POORHLTH", "EXERANY2",

    # BMI / anthropometrics
    # Keep: _BMI5 (continuous computed BMI)
    # Raw height and weight in all unit encodings are redundant as we have _BMI5. 
    # _BMI5CAT and _RFBMI5 are redundant to _BMI5.
    "WEIGHT2", "HEIGHT3", "HTIN4", "HTM4", 
    "WTKG3", "_BMI5CAT", "_RFBMI5",

    # Race / ethnicity
    # Keep: _RACE (8-category combined variable covering all race variants)
    "_RACEG21", "_RACEGR3", "_RACEPRV", "_MRACE1", 
    "_IMPRACE", "_CHISPNC", "_CRACE1", "_HISPANC",

    # Age
    # Keep: _AGE80 (Alternatives are encoded in age groups, but _AGE80 is a continuous number 
    # that gives us more precise information about the respondent's age)
    "_AGE65YR", "_AGE_G", "_AGEG5YR", "_LCSAGE",

    # Smoking
    # Keep: _SMOKER3 (Derived variable that combines current / former / never / every day smoking status)
    # Keep: LCSNUMC_ (preciese number of cigarettes smoked per day)
    # Raw inputs SMOKE100 and SMOKDAY2 are fully absorbed by _SMOKER3.
    # _RFSMOK3 is a binary collapse of _SMOKER3. USENOW3, LASTSMK2,
    "_RFSMOK3", "USENOW3", "LASTSMK2", "STOPSMK2", "LCSNUMCG",
    "HEATTBCO", "SMOKE100", "SMOKDAY2", "_PACKDAY", "_LCSSMKG",
    "_PACKYRS",

    # E-cigarettes / vaping
    # Keep: ECIGNOW3 (Has all 3-category current / former / never status)
    "_CURECI3", "MENTCIGS", "MENTECIG",
    
    # Marijuana / cannabis
    # Keep: MARIJAN1 (Give us not just the status but precise amount of consumption days)
    "MARJEAT", "MARJDAB", "MARJOTHR", "MARJSMOK", "MARJVAPE", "USEMRJN4",

    # Alcohol
    # Keep: _DRNKWK3 (Calculated total number of alcoholic beverages consumed per week, 
    # while the alternatives are coarser categories or binary variables)
    "_RFBING6", "DRNKANY6", "ALCDAY4", "DRNK3GE5", 
    "MAXDRNKS", "DROCDY4_", "_RFDRHV9", "AVEDRNK4",

    # Education / Income
    # Keep: EDUCA / INCOME3 (EDUCA and INCOME3 respectively provide a more detailed range of education and income levels)
    "_EDUCAG", "_INCOMG1", 

    # Health insurance / access
    # Keep: PRIMINS2 , PERSDOC3, CHECKUP1
    "MEDCOST1", "_HLTHPL2" , "_HCVU654",

    # Sex
    # Keep: _SEX
    "SEXVAR",

    # Asthma
    # Keep: _ASTHMS1 (Computed Asthma Status, covers all 3 current, former and never asthma status)
    "_LTASTH1", "_CASTHM1", "CASTHDX2", "CASTHNO2", "ASTHNOW", "ASTHMA3", 

    # Cancer / Lung cancer screening test
    # Keep: _LCSCTSN, CERVSCRN, 
    "CSRVDOC1", "CSRVRTRN", "CSRVCLIN", "LCSSCNCR", "LCSCTSC1", "_LCSPSTF",
    "LCSCTWHN", 

    # Dental / oral health
    # Keep: LASTDEN4, RMVTETH4
    "_EXTETH3", "_DENVST3", "_ALTETH3",

    # PSA test follow-ups
    # Keep: PSATEST1 (ever had PSA test)
    "PSATIME1", "PCPSARS2", "PSASUGS1",

    # Mammography / cervical screening
    # Keep: HOWLONG
    "_SGMS102", "_SGMSCP2", "_CLNSCP2", "_MAM402Y", "_RFMAM23",
    "_CRVSCRN", "_RFPAP37",

    # Flu shot
    # FLUSHOT7 (as it has no age restriction, while _FLSHOT7 is only for 65+)
    "_FLSHOT7", "_PNEUMO3", "FLSHTMY3", "IMFVPLA5", "HIVTSTD3",

    # Colorectal screening
    # Keep: COLNSIGM (handles both sigmoidoscopy and colonoscopy, as well as both)
    "_HADSIGM", "_HADCOLN", "VIRCOLO1", "_VIRCOL2", "_RFBLDS6", "_STOLDN2",
    "STOOLDN2", "_CRCREC3", "BLDSTFIT", "SDNATES1", "VCLNTES2", "SMALSTOL",
    "_SBONTI2", "HADSIGM4", "LASTSIG4",
    
    # Arthritis
    # Keep: HAVARTH4
    "_DRDXAR2", "ARTHEXER", "CHKHEMO3", 

    # Urbanicity
    # Keep: _URBSTAT
    "_METSTAT", "MSCODE",

    # HIV/AIDS
    # Keep: HIVTST7
    "_AIDTST4", "_HPV5YR1", "_PAPHPV1", "HPVADSH1",

    # Angina or Coronary Heart Disease
    # Keep: _MICHD and CVDINFR4
    "CVDCRHD4",
], inplace=True)

print("Dataset after dropping redundant features:", df.shape)
df.head(1)

Dataset after dropping redundant features: (456218, 115)

,_STATE,GENHLTH,PHYSHLTH,MENTHLTH,PRIMINS2,PERSDOC3,CHECKUP1,LASTDEN4,RMVTETH4,CVDINFR4,CVDSTRK3,CHCSCNC1,CHCOCNC1,CHCCOPD3,ADDEPEV3,CHCKDNY2,HAVARTH4,DIABETE4,DIABAGE4,MARITAL,EDUCA,VETERAN3,EMPLOY1,INCOME3,PREGNANT,DEAF,BLIND,DECIDE,DIFFWALK,DIFFDRES,DIFFALON,HADMAM,HOWLONG,CERVSCRN,CRVCLCNC,CRVCLPAP,CRVCLHPV,HADHYST2,COLNSIGM,COLNTES1,SIGMTES1,COLNCNCR,STOLTEST,ECIGNOW3,LCSFIRST,FLUSHOT7,PNEUVAC4,HIVTST7,HIVRISK5,PDIABTS1,PREDIAB2,DIABTYPE,INSULIN1,EYEEXAM1,DIABEYE1,DIABEDU1,FEETSORE,SHINGLE2,HPVADVC4,TETANUS1,CNCRDIFF,CNCRAGE,CNCRTYP2,CSRVTRT3,CSRVPAIN,PSATEST1,CIMEMLO1,CDWORRY,CDDISCU1,CDHOUS1,CDSOCIA1,ACEDEPRS,ACEDRINK,ACEDRUGS,ACEPRISN,ACEDIVRC,ACEPUNCH,ACEHURT1,ACESWEAR,ACETOUCH,ACETTHEM,ACEHVSEX,ACEADSAF,ACEADNED,LSATISFY,EMTSUPRT,SDLONELY,SDHEMPLY,FOODSTMP,SDHFOOD1,SDHBILLS,SDHUTILS,SDHTRNSP,HOWSAFE1,MARIJAN1,SSBSUGR2,SSBFRUT3,SOMALE,SOFEMALE,_URBSTAT,_TOTINDA,_MICHD,_ASTHMS1,_RACE,_SEX,_AGE80,_BMI5,_SMOKER3,LCSLAST_,LCSNUMC_,_LCSYSMK,_LCSYQTS,_LCSELIG,_LCSCTSN,_DRNKWK3
0,1.0,3.0,2.0,88.0,3.0,2.0,1.0,1.0,1.0,2.0,0,1.0,2.0,2.0,2.0,2.0,1.0,3.0,NaN,3.0,4.0,2.0,7.0,99.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,1.0,2.0,1.0,2.0,1.0,1.0,3.0,NaN,1.0,7.0,1.0,NaN,1.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,5.0,2.0,2.0,5.0,2.0,2.0,2.0,1.0,NaN,NaN,NaN,NaN,2.0,1.0,1.0,2.0,3.0,1.0,2.0,78.0,2249.0,4.0,NaN,NaN,NaN,NaN,2.0,NaN,5.397605e-79

In [54]:
# Compare the results of correlation analysis after removing redundant features
# from feature_analysis import find_high_correlation_pairs

# pairs_df = find_high_correlation_pairs(df, threshold=0.80, sample_n = 50_000, random_state = 42)
# print(pairs_df.to_string(index=False))

In [55]:
# Features categorised per the Overleaf report tables
# Table 1 (tab:stroke_feature_rationale) — included features
included_features = [
    # Demographic
    '_STATE', '_SEX', '_RACE', '_AGE80',
    'EDUCA', 'INCOME3', 'MARITAL', 'EMPLOY1', 'VETERAN3', 'PREGNANT',
    '_URBSTAT',

    # General health
    'GENHLTH', 'PHYSHLTH', 'MENTHLTH',

    # Lifestyle / behavioural
    '_TOTINDA', '_BMI5',
    '_SMOKER3', 'LCSFIRST', 'LCSLAST_', 'LCSNUMC_', '_LCSYSMK', '_LCSYQTS',
    '_LCSELIG', '_LCSCTSN',
    'ECIGNOW3', 'MARIJAN1',
    '_DRNKWK3',
    'SSBSUGR2', 'SSBFRUT3',

    # Diabetes
    'DIABETE4', 'DIABAGE4', 'DIABTYPE', 'PDIABTS1', 'PREDIAB2',
    'INSULIN1', 'EYEEXAM1', 'DIABEYE1', 'DIABEDU1', 'FEETSORE',

    # Clinical comorbidities
    '_ASTHMS1', 'CHCCOPD3', 'CHCKDNY2', 'HAVARTH4', 'ADDEPEV3',
    'CHCOCNC1', 'CNCRTYP2', 'CSRVTRT3', 'CNCRAGE', 'CSRVPAIN',

    # Healthcare access
    'PRIMINS2', 'PERSDOC3', 'LASTDEN4', 'RMVTETH4',

    # Female-specific
    'HADHYST2',

    # Adverse childhood experiences (ACEs)
    'ACEDEPRS', 'ACEDRINK', 'ACEDRUGS', 'ACEPRISN', 'ACEDIVRC',
    'ACEPUNCH', 'ACEHURT1', 'ACESWEAR',
    'ACETOUCH', 'ACETTHEM', 'ACEHVSEX',
    'ACEADSAF', 'ACEADNED',

    # Social / psychosocial
    'LSATISFY', 'EMTSUPRT', 'SDLONELY',
]

# Table 2 (tab:stroke_feature_exclusion_rationale) — excluded features
excluded_features = [
    # Healthcare engagement proxies with no independent stroke signal
    'CHECKUP1',
    'HADMAM', 'HOWLONG',
    'CERVSCRN', 'CRVCLCNC', 'CRVCLPAP', 'CRVCLHPV',
    'COLNSIGM', 'COLNTES1', 'SIGMTES1', 'COLNCNCR', 'STOLTEST',
    'HIVTST7', 'HIVRISK5',
    'PSATEST1',
    # Vaccines — no causal stroke risk
    'SHINGLE2', 'HPVADVC4', 'TETANUS1',
    # Social-needs / material-hardship — redundant with income/education
    'FOODSTMP', 'SDHFOOD1', 'SDHBILLS', 'SDHUTILS', 'SDHTRNSP',
    # Weak / non-specific cancer
    'CHCSCNC1',
]

df.drop(columns=excluded_features, inplace=True)
print("Dataset after dropping excluded features:", df.shape)

# Table 3 (tab:stroke_feature_uncertainty_rationale) — uncertain features
uncertain_features = [
    # Post-stroke functional limitations (temporal ambiguity)
    'DIFFWALK', 'DIFFDRES', 'DIFFALON',
    # Cognitive items (pre- vs post-stroke unclear)
    'CIMEMLO1', 'CDWORRY', 'CDDISCU1', 'CDHOUS1', 'CDSOCIA1', 'DECIDE',
    # Social-needs items with directional ambiguity
    'SDHEMPLY',
    # Vaccinations with uncertain directionality
    'FLUSHOT7', 'PNEUVAC4',
    # Sensory / neighbourhood items
    'DEAF', 'BLIND', 'HOWSAFE1',
    # Sexual orientation
    'SOMALE', 'SOFEMALE',
    # Cancer count (likely redundant)
    'CNCRDIFF',
    # CVD variables (overlap between _MICHD, CVDINFR4, CVDCRHD4)
    '_MICHD', 'CVDINFR4', 'CVDCRHD4',
]

Dataset after dropping excluded features: (456218, 91)

In [56]:
for col in df.columns:
    print(f"{col}: {df[col].unique()}")

_STATE: [ 1.  2.  4.  5.  6.  8.  9. 10. 11. 12. 13. 15. 16. 17. 18. 19. 20. 21.
 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35. 36. 37. 38. 39.
 40. 41. 42. 44. 45. 46. 48. 49. 50. 51. 53. 54. 55. 56. 66. 72. 78.]
GENHLTH: [ 3.  1.  2.  4.  5.  7.  9. nan]
PHYSHLTH: [ 2. 88. 30.  7.  5. 14.  1. 99. 25. 20. 77.  6.  3.  4. 15. 10.  8. 27.
 12. 29. 28. 21.  9. 19. 16. 23. 18. 17. 26. 24. 11. 22. 13. nan]
MENTHLTH: [88. 15.  1. 77. 30.  2.  8. 10.  7.  6.  5.  4.  9. 99. 25. 20.  3. 29.
 11. 12. 14. 26. 17. 23. 21. 28. 18. 22. 13. 19. 16. 27. 24. nan]
PRIMINS2: [ 3.  1.  5.  7. 77. 99.  9.  2. 10. 88.  4.  6.  8. nan]
PERSDOC3: [ 2.  1.  3.  9.  7. nan]
LASTDEN4: [1. 4. 2. 3. 7. 8. 9.]
RMVTETH4: [ 1.  2.  8.  3.  7.  9. nan]
CVDINFR4: [2. 1. 7. 9.]
CVDSTRK3: [0 1]
CHCOCNC1: [ 2.  1.  7.  9. nan]
CHCCOPD3: [ 2.  1.  7.  9. nan]
ADDEPEV3: [ 2.  1.  7.  9. nan]
CHCKDNY2: [ 2.  1.  7.  9. nan]
HAVARTH4: [ 1.  2.  7.  9. nan]
DIABETE4: [ 3.  1.  4.  2.  7.  9. nan]
DIABAGE4: [nan 44. 58. 33. 50. 55. 70. 98. 62. 38. 47. 45. 35. 53. 59. 73. 32. 57.
 52. 60. 20. 65. 68. 51. 30. 75. 40. 72. 61. 76. 78. 28. 42. 29. 69. 67.
 56. 49. 80. 34. 54. 36. 63. 77. 25. 66. 94. 48. 99. 43. 16. 41. 64. 74.
 83. 39. 71. 26. 21. 18. 37. 24. 22. 31. 27. 46.  9. 15. 19.  5. 82. 10.
 23. 17.  3. 13. 79.  7. 12. 11.  1.  4. 85.  6. 14. 86.  8. 90. 87. 84.
 81. 92.  2. 95. 88. 89. 91. 93. 97.]
MARITAL: [ 3.  1.  6.  5.  2.  9.  4. nan]
EDUCA: [ 4.  6.  5.  3.  2.  9.  1. nan]
VETERAN3: [ 2.  1. nan  9.  7.]
EMPLOY1: [ 7.  1.  8.  5. nan  2.  6.  3.  9.  4.]
INCOME3: [99. 11.  6.  3.  9.  5.  7.  8.  2. 10. 77. nan  4.  1.]
PREGNANT: [nan  2.  1.  9.  7.]
DEAF: [ 2.  1. nan  7.  9.]
BLIND: [ 2.  1. nan  9.  7.]
DECIDE: [ 2.  1. nan  7.  9.]
DIFFWALK: [ 2.  1. nan  7.  9.]
DIFFDRES: [ 2.  1. nan  9.  7.]
DIFFALON: [ 2.  1. nan  7.  9.]
HADHYST2: [ 1. nan  2.  9.  7.]
ECIGNOW3: [ 1.  4. nan  3.  7.  2.  9.]
LCSFIRST: [ nan  25.  14.  10.  22.  18.  11. 888.  20.  17.  15.  32.  13.  16.
   9.  12.  28.  19.  30. 777.  24.  34.  27. 999.  21.  38.  23.  35.
  40.  29.  33.  26.   8.  37.   4.  42.  31.  43.   2.   7.  49.   6.
  50.  44.  51.  52.  55.   3.  36.   5.  60.  41.  45.  69.  48.  46.
  47.  58.  39.  63.  53.  78.  70.  65.  61.   1.  77.  54.  62.  59.
  56.  76.  64.  57.  75.  79.  80.  71.  66.  68.  67.  72.  99.  81.]
FLUSHOT7: [ 1.  2. nan  9.  7.]
PNEUVAC4: [ 2.  1. nan  7.  9.]
PDIABTS1: [nan  1.  2.  7.  8.  5.  6.  4.  3.  9.]
PREDIAB2: [nan  1.  3.  9.  7.  2.]
DIABTYPE: [nan  2.  7.  9.  1.]
INSULIN1: [nan  2.  1.  9.  7.]
EYEEXAM1: [nan  3.  1.  2.  4.  8.  9.  7.]
DIABEYE1: [nan  1.  7.  2.  3.  4.  8.  9.]
DIABEDU1: [nan  8.  1.  6.  7.  5.  2.  9.  3.  4.]
FEETSORE: [nan  2.  1.  9.  7.]
CNCRDIFF: [nan  1.  3.  2.  7.  9.]
CNCRAGE: [nan 75. 80. 30. 74. 60. 82. 76. 55. 98. 50. 65. 70. 56. 62. 69. 61. 99.
 33. 40. 58. 52. 49. 72. 86. 71. 35. 79. 36. 68. 48. 85. 77. 46. 78. 84.
 67. 34. 63. 43. 66. 83. 59. 41. 51. 64. 45. 73. 47. 88. 42. 38. 53. 17.
 90. 31. 24. 54. 28. 19. 39. 23. 57. 25. 37. 44. 12. 29. 18. 27. 26. 21.
  2. 11. 20. 32. 22. 16.  1. 81. 87. 10. 15.  7.  6. 92. 13. 14.  8.  9.
 89.  5.  4.  3. 94. 93. 91. 95.]
CNCRTYP2: [nan 27. 22. 20. 21. 14.  5. 30. 16. 10. 15. 23. 28. 77.  7.  8.  6.  1.
 25.  3. 99.  4. 26. 12. 29. 19.  2. 18. 13. 17.  9. 11. 24.]
CSRVTRT3: [nan  2.  5.  1.  4.  7.  9.  3.]
CSRVPAIN: [nan  1.  2.  7.  9.]
CIMEMLO1: [ 2.  1. nan  7.  9.]
CDWORRY: [nan  2.  1.  7.  9.]
CDDISCU1: [nan  1.  2.  7.  9.]
CDHOUS1: [nan  2.  1.  7.  9.]
CDSOCIA1: [nan  1.  2.  7.  9.]
ACEDEPRS: [nan  2.  1.  7.  9.]
ACEDRINK: [nan  2.  1.  9.  7.]
ACEDRUGS: [nan  2.  1.  7.  9.]
ACEPRISN: [nan  2.  1.  7.  9.]
ACEDIVRC: [nan  2.  1.  7.  9.  8.]
ACEPUNCH: [nan  1.  3.  2.  9.  7.]
ACEHURT1: [nan  1.  3.  2.  9.  7.]
ACESWEAR: [nan  1.  3.  2.  9.  7.]
ACETOUCH: [nan  1.  3.  2.  9.  7.]
ACETTHEM: [nan  1.  3.  2.  9.  7.]
ACEHVSEX: [nan  1.  3.  9.  2.  7.]
ACEADSAF: [nan  5.  4.  1.  3.  2.  7.  9.]
ACEADNED: [nan  5.  3.  4.  2.  9.  1.  7.]
LSATISFY: [ 1.  2.  3. nan  9.  4.  7.]
EMTSUPRT: [ 1.  2.  4.  5.  3.  7. nan  9.]
SDLONELY: [ 5.  1.  2.  3.  4. nan  7.  9.]
SDHEMPLY: [ 2. nan  1.  7.  9.]
HOWSAFE1: [ 1.  2. nan  7.  4.  3.  9.]
MARIJAN1: [nan 88. 30. 25.  1. 20.  5. 15.  3. 27.  2. 99. 26. 29. 10.  8.  4.  7.
 77.  6. 28. 16. 18. 12.  9. 14. 23. 21. 13. 24. 11. 22. 17. 19.]
SSBSUGR2: [ nan 302. 888. 103. 201. 101. 301. 102. 105. 303. 104. 203. 999. 304.
 310. 305. 202. 223. 107. 204. 315. 191. 205. 308. 777. 312. 224. 330.
 120. 207. 106. 306. 206. 230. 112. 325. 130. 307. 320. 360. 110. 314.
 250. 311. 399. 108. 324. 196. 221. 131. 199. 309. 212. 316. 115. 215.
 328. 121. 333. 210. 150. 299. 313. 329. 327. 321. 317. 220. 208. 233.
 318. 124. 323. 214. 129. 109. 118. 116. 326. 170. 322. 340. 336. 391.
 123. 240. 355. 122. 125. 209. 111. 113. 382. 335. 346. 222. 114. 292.
 133. 249. 390. 350. 395. 388. 331. 345. 225. 347. 141. 385. 117. 291.
 198.]
SSBFRUT3: [ nan 888. 301. 201. 101. 302. 102. 103. 999. 310. 304. 120. 303. 202.
 777. 203. 315. 205. 305. 330. 112. 106. 105. 204. 107. 104. 320. 312.
 131. 114. 309. 130. 307. 350. 314. 306. 325. 318. 110. 215. 206. 316.
 323. 308. 207. 210. 321. 199. 115. 399. 109. 208. 317. 214. 108. 150.
 327. 324. 335. 360. 328. 340. 322. 211. 329. 225. 230. 128. 125. 221.
 153. 242. 212. 124. 313. 338. 220. 122. 113. 326. 299. 311. 331. 291.
 222. 209. 364. 118. 260. 224. 140. 217. 388. 116. 228. 390. 213.]
SOMALE: [nan  2.  3.  9.  1.  4.  7.]
SOFEMALE: [ 2. nan  1.  3.  4.  9.  7.]
_URBSTAT: [ 1.  2. nan]
_TOTINDA: [1. 2. 9.]
_MICHD: [ 2.  1. nan]
_ASTHMS1: [3. 2. 1. 9.]
_RACE: [1. 7. 2. 4. 8. 9. 6. 3. 5.]
_SEX: [2. 1.]
_AGE80: [78. 80. 59. 47. 54. 71. 68. 70. 72. 75. 67. 77. 63. 76. 74. 62. 79. 60.
 69. 66. 56. 73. 65. 61. 21. 64. 44. 49. 45. 50. 58. 55. 51. 43. 52. 57.
 48. 53. 42. 37. 25. 39. 35. 41. 27. 20. 24. 29. 26. 19. 46. 36. 30. 33.
 28. 23. 31. 34. 32. 40. 38. 18. 22.]
_BMI5: [2249. 2583. 2253. ... 4246. 4595. 4065.]
_SMOKER3: [4. 3. 1. 9. 2.]
LCSLAST_: [nan 27. 10. 72. 68. 30. 38. 50. 45. 55. 32. 46. 65. 22. 60. 25. 16. 57.
 26. 66. 24. 40. 34. 21. 58. 79. 36. 80. 63. 33. 23. 20. 29. 51. 42. 35.
 47. 44. 70. 37. 18. 75. 48. 43. 69. 73. 81. 62. 71. 28. 52. 12. 64. 53.
 61. 49. 39. 56. 19. 59. 54. 31. 67. 17. 41. 15. 77. 74. 78. 76. 14. 13.
 11.  4.  9.  2.  6.  3.  7.  5.  1.  8.]
LCSNUMC_: [ nan  20.  15.   7.   4.   5.  12.  10.  40.  30.   2.   3.  60.  16.
   1.   6.  35.  50.  18.  25.   8.  11.  13.   9.  70.  29.  14.  24.
  23.  72. 125.  28. 100.  17.  80.  45.  75. 140. 115.  27.  19.  21.
 300.  22. 200. 110. 201.  32. 143. 106. 107.  46. 150. 103.  90.  77.
  48.  49.  26.  55. 120.  88.  65. 104.  36. 105. 118. 102.  31. 101.
 210. 202. 130.  33. 205. 108. 113. 175.  43.  74. 203.  83.  82.  67.
  84.  39. 290.  47.  34. 152.  42.  56. 230.  85. 260. 135. 204. 209.
  68. 180. 155. 153.  52. 156.  73.  38.  54.  63.  53.  58. 225.  71.
  62.  57.  44.  99.  37.  76.  78. 160. 215.  66.  64. 190. 490.  51.]
_LCSYSMK: [           nan 2.00000000e+00 4.50000000e+01 5.39760535e-79
 5.00000000e+01 5.70000000e+01 1.00000000e+01 1.80000000e+01
 3.00000000e+01 1.20000000e+01 4.20000000e+01 1.60000000e+01
 4.70000000e+01 2.80000000e+01 3.10000000e+01 3.20000000e+01
 7.00000000e+00 1.00000000e+00 4.00000000e+00 3.30000000e+01
 5.60000000e+01 3.90000000e+01 1.10000000e+01 4.80000000e+01
 6.00000000e+01 4.10000000e+01 6.00000000e+00 4.40000000e+01
 4.00000000e+01 2.10000000e+01 3.40000000e+01 2.20000000e+01
 8.00000000e+00 4.30000000e+01 2.40000000e+01 6.10000000e+01
 4.60000000e+01 3.60000000e+01 5.80000000e+01 2.90000000e+01
 2.00000000e+01 3.00000000e+00 6.40000000e+01 5.40000000e+01
 5.00000000e+00 4.90000000e+01 2.60000000e+01 6.30000000e+01
 5.30000000e+01 1.70000000e+01 5.50000000e+01 1.40000000e+01
 2.70000000e+01 5.20000000e+01 2.30000000e+01 3.80000000e+01
 3.70000000e+01 3.50000000e+01 6.20000000e+01 2.50000000e+01
 6.50000000e+01 6.60000000e+01 7.00000000e+01 5.10000000e+01
 1.90000000e+01 9.00000000e+00 1.30000000e+01 1.50000000e+01
 7.90000000e+01 6.80000000e+01 6.70000000e+01 5.90000000e+01
 8.20000000e+01 7.70000000e+01 7.60000000e+01 7.10000000e+01
 6.90000000e+01 7.20000000e+01 7.30000000e+01 7.50000000e+01
 7.40000000e+01 8.10000000e+01 9.40000000e+01 7.80000000e+01
 8.60000000e+01 8.80000000e+01 9.00000000e+01 8.50000000e+01
 8.90000000e+01 8.30000000e+01]
_LCSYQTS: [            nan  5.30000000e+01  8.00000000e+01  5.39760535e-79
  3.00000000e+00  5.10000000e+01  3.70000000e+01  2.60000000e+01
  2.90000000e+01  5.00000000e+00  4.80000000e+01  2.70000000e+01
  4.20000000e+01  1.00000000e+01  4.40000000e+01  1.50000000e+01
  3.60000000e+01  4.50000000e+01  4.90000000e+01  2.00000000e+01
  1.10000000e+01  4.00000000e+01  6.00000000e+01  3.00000000e+01
  2.50000000e+01  3.80000000e+01  2.40000000e+01  3.20000000e+01
  5.00000000e+01  3.50000000e+01  1.40000000e+01  2.00000000e+00
  6.00000000e+00  4.10000000e+01  2.20000000e+01  4.60000000e+01
  5.20000000e+01  5.90000000e+01  5.50000000e+01  1.60000000e+01
  3.90000000e+01  6.10000000e+01  3.40000000e+01  9.00000000e+00
  1.70000000e+01  6.70000000e+01  3.10000000e+01  2.30000000e+01
  4.30000000e+01  2.10000000e+01  4.70000000e+01  3.30000000e+01
  1.30000000e+01  2.80000000e+01  1.90000000e+01  1.00000000e+00
  5.80000000e+01  6.20000000e+01  5.40000000e+01  6.30000000e+01
  4.00000000e+00  5.60000000e+01  7.00000000e+00  1.20000000e+01
  8.00000000e+00  1.80000000e+01  5.70000000e+01  6.60000000e+01
  6.50000000e+01 -6.00000000e+00  6.90000000e+01  6.80000000e+01
 -2.00000000e+01 -2.00000000e+00 -1.10000000e+01 -1.20000000e+01
  7.00000000e+01  7.10000000e+01 -1.00000000e+01 -7.00000000e+00
 -4.00000000e+00  6.40000000e+01 -1.70000000e+01 -1.00000000e+00
  7.40000000e+01  7.30000000e+01  7.60000000e+01 -5.00000000e+00
 -9.00000000e+00 -3.00000000e+00 -1.40000000e+01  7.80000000e+01
  8.30000000e+01  7.70000000e+01  7.50000000e+01  7.20000000e+01
 -1.80000000e+01 -8.00000000e+00 -3.00000000e+01 -2.20000000e+01
 -1.30000000e+01 -1.50000000e+01 -1.60000000e+01 -2.40000000e+01
  8.10000000e+01 -2.10000000e+01  7.90000000e+01 -1.90000000e+01
 -2.50000000e+01]
_LCSELIG: [ 2.  1. nan]
_LCSCTSN: [nan  4.  3.  2.  1.]
_DRNKWK3: [5.39760535e-79 1.40000000e+03 3.50000000e+02 9.99000000e+04
 4.70000000e+01 1.00000000e+02 9.33000000e+02 6.00000000e+02
 1.00000000e+03 1.40000000e+02 8.00000000e+02 2.80000000e+03
 1.17000000e+02 7.00000000e+02 3.00000000e+02 2.30000000e+01
 1.87000000e+02 2.00000000e+02 9.30000000e+01 2.33000000e+02
 2.10000000e+02 1.20000000e+03 7.00000000e+01 4.20000000e+02
 4.00000000e+02 3.73000000e+02 2.80000000e+02 1.50000000e+03
 5.83000000e+02 5.00000000e+02 4.67000000e+02 1.16700000e+03
 8.17000000e+02 1.80000000e+03 3.60000000e+03 5.60000000e+02
 2.24000000e+03 2.10000000e+03 4.20000000e+03 1.05000000e+03
 1.60000000e+03 4.90000000e+02 8.40000000e+02 4.90000000e+03
 2.00000000e+03 1.12000000e+03 1.96000000e+03 1.86700000e+03
 5.60000000e+03 1.75000000e+03 1.63300000e+03 9.00000000e+02
 6.53000000e+02 1.14300000e+03 1.63000000e+02 3.50000000e+03
 7.28000000e+03 9.80000000e+02 3.27000000e+02 2.42700000e+03
 7.47000000e+02 3.00000000e+03 8.40000000e+03 2.45000000e+03
 2.50000000e+03 1.07300000e+03 2.33300000e+03 2.91700000e+03
 1.30700000e+03 1.26000000e+03 1.68000000e+03 6.77000000e+02
 4.50000000e+03 3.36000000e+03 7.70000000e+02 2.40000000e+03
 4.08300000e+03 1.19000000e+04 1.35300000e+03 7.00000000e+03
 3.78000000e+03 2.61300000e+03 4.48000000e+03 1.68000000e+04
 2.05300000e+03 3.92000000e+03 3.38300000e+03 4.00000000e+03
 6.30000000e+02 3.73300000e+03 2.57000000e+02 1.82000000e+03
 2.03000000e+03 3.26700000e+03 2.70700000e+03 5.83300000e+03
 1.12000000e+04 2.10000000e+04 1.47000000e+03 4.66700000e+03
 5.37000000e+02 1.02700000e+03 1.16670000e+04 1.54000000e+03
 2.52000000e+03 6.00000000e+03 5.13000000e+02 3.97000000e+02
 6.30000000e+03 2.68300000e+03 1.19000000e+03 6.07000000e+02
 5.00000000e+03 4.06000000e+03 2.80000000e+04 1.40000000e+04
 6.53300000e+03 5.25000000e+03 8.00000000e+03 5.22700000e+03
 6.86000000e+03 4.80000000e+03 4.57300000e+03 8.96000000e+03
 6.65000000e+03 2.52000000e+04 9.00000000e+03 5.32000000e+04
 2.26800000e+04 3.15000000e+03 1.26000000e+04 2.94000000e+03
 1.21300000e+03 7.93000000e+02 5.40000000e+03 1.61000000e+03
 3.30000000e+03 9.10000000e+03 7.56000000e+03 1.05000000e+04
 5.41300000e+03 1.49300000e+03 3.90000000e+03 3.03000000e+02
 1.89000000e+03 4.20000000e+04 5.95000000e+03 7.20000000e+03
 9.33300000e+03 7.35000000e+03 7.50000000e+03 2.14700000e+03
 1.47000000e+04 3.20000000e+03 4.85300000e+03 9.91700000e+03
 1.07100000e+04 4.73700000e+03 2.73000000e+03 2.12300000e+03
 9.80000000e+03 1.30670000e+04 1.75000000e+04 8.12000000e+03
 1.20000000e+04 1.50000000e+04 2.28000000e+04 9.10000000e+02
 7.70000000e+03 8.87000000e+02 1.35000000e+04 5.88000000e+03
 4.83000000e+04 4.41000000e+03 1.25000000e+04 3.50000000e+04
 3.08000000e+03 5.46000000e+03 4.37500000e+04 5.97300000e+03
 2.12800000e+04 3.36000000e+04 1.00000000e+04 9.24000000e+03
 5.04000000e+03 2.56700000e+03 7.80000000e+03 1.98300000e+03
 6.72000000e+03 1.86670000e+04 2.70000000e+03 7.93300000e+03
 6.16000000e+03 4.90000000e+04 7.84000000e+03 2.60000000e+03
 5.67000000e+03 1.34400000e+04 1.58700000e+03 2.40000000e+04
 1.00800000e+04 1.10000000e+03 3.54670000e+04 2.94000000e+04
 3.22000000e+03 2.28700000e+03 3.17300000e+03 1.56800000e+04
 2.77700000e+03 6.40000000e+03 2.24000000e+04 8.75000000e+03
 1.23200000e+04 5.13300000e+03 2.98700000e+03 7.14000000e+03
 3.22000000e+04 2.38000000e+03 6.67300000e+03 4.29300000e+03
 1.96000000e+04 3.00000000e+04 3.64000000e+03 1.28300000e+03
 1.82000000e+04 1.96230000e+04 1.44000000e+04 1.08000000e+04
 2.33330000e+04 5.50000000e+03 3.03300000e+03 2.00000000e+04
 1.56000000e+04 1.51700000e+03 8.16700000e+03 3.11270000e+04
 4.24700000e+03 1.45830000e+04 1.54000000e+04 1.04530000e+04
 2.09070000e+04 7.60000000e+03 3.57000000e+03 1.02000000e+04
 6.06700000e+03 3.15000000e+04 3.85000000e+03 1.62400000e+04
 3.59300000e+03 6.09000000e+03 2.20000000e+03 6.41700000e+03
 3.08000000e+04 4.43000000e+02 2.45000000e+04 5.20000000e+03
 1.24130000e+04 4.10700000e+03 9.60000000e+03 3.96700000e+03
 1.10000000e+04 2.17000000e+03 1.01500000e+04 1.28330000e+04
 5.10000000e+03 5.25000000e+04 3.75700000e+03 6.76700000e+03
 2.21700000e+03 1.57730000e+04 7.46700000e+03 4.40000000e+03
 1.60000000e+04 1.80000000e+04 1.41870000e+04 1.52000000e+04
 1.22500000e+04 6.44000000e+03 1.57500000e+04 8.42300000e+03
 5.71700000e+03 9.14700000e+03 2.62500000e+04]

In [57]:
# BRFSS 2024 encodes "Don't know / Refused / Missing" responses with specific codes that vary by question.
# The problem is that a high value for those responses can be misinterpreted by models as meaningful data (have a high weight on the model).
# The code below replaces those specific codes with NaN, and in some cases 0 (for "none" or "never" responses).

# Handle don't know / unsure / refused / none / never

# 7/9 → NaN (don't know / refused)
_cols_dk = [
    "GENHLTH", "PERSDOC3", "CVDINFR4", "CHCOCNC1", "CHCCOPD3",
    "ADDEPEV3", "CHCKDNY2", "HAVARTH4", "DIABETE4", "VETERAN3",
    "PREGNANT", "DEAF", "BLIND", "DECIDE", "DIFFWALK", "DIFFDRES", "DIFFALON",
    "HADHYST2", "ECIGNOW3", "FLUSHOT7", "PNEUVAC4", "PREDIAB2",
    "DIABTYPE", "INSULIN1", "FEETSORE", "CNCRDIFF", "CSRVTRT3", "CSRVPAIN", 
    "CIMEMLO1", "CDWORRY", "CDDISCU1", "CDHOUS1", "CDSOCIA1", "ACEDEPRS", "ACEDRINK", "ACEDRUGS",
    "ACEPRISN", "ACEPUNCH", "ACEHURT1", "ACESWEAR", "ACETOUCH", "ACETTHEM",
    "ACEHVSEX", "ACEADSAF", "ACEADNED", "LSATISFY", "EMTSUPRT", "SDLONELY",
    "SDHEMPLY", "HOWSAFE1", "SOMALE", "SOFEMALE"
]

for col in _cols_dk:
    df[col] = df[col].replace({7: np.nan, 9: np.nan})

# 7/9 → NaN, 8 → 0 (none/never)
_cols_dk_none = [
    "LASTDEN4", "RMVTETH4", "DIABEYE1", "DIABEDU1", "PDIABTS1",
]
for col in _cols_dk_none:
    df[col] = df[col].replace({7: np.nan, 8: 0, 9: np.nan})

# 77/88/99 → NaN/0/NaN
for col in ["PRIMINS2", "PHYSHLTH", "MENTHLTH", "MARIJAN1"]:
    df[col] = df[col].replace({77: np.nan, 88: 0, 99: np.nan})

# 77/99 → NaN (no 88 code)
for col in ["CNCRTYP2", "INCOME3"]:
    df[col] = df[col].replace({77: np.nan, 99: np.nan})

# 777/888/999 → NaN/0/NaN
for col in ["SSBSUGR2", "SSBFRUT3"]:
    df[col] = df[col].replace({777: np.nan, 888: 0, 999: np.nan})

# 98/99 → NaN (age fields)
for col in ["DIABAGE4", "CNCRAGE"]:
    df[col] = df[col].replace({98: np.nan, 99: np.nan})

# 9 → NaN (where 9 stands for Don't know / Refused / Missing)
for col in ["_TOTINDA", "_ASTHMS1", "_RACE", "_SMOKER3", "EDUCA", "MARITAL"]:
    df[col] = df[col].replace({9: np.nan})

# Irregular codings — handled individually
df["LCSFIRST"] = df["LCSFIRST"].replace({777: np.nan, 888: np.nan, 999: np.nan})
df["ACEDIVRC"] = df["ACEDIVRC"].replace({7: np.nan, 8: 3, 9: np.nan})
df["EYEEXAM1"] = df["EYEEXAM1"].replace({6: np.nan, 7: np.nan, 8: np.nan, 9: np.nan})
df["_DRNKWK3"] = df["_DRNKWK3"].replace({99900: np.nan})

# BMI and alcohol consumption are stored times 100 (e.g. 2249 = BMI 22.49, 1000 = 10.00 drinks per week)
# Scale them to the normal range to avoid misleading
df['_BMI5'] = df['_BMI5'] / 100
df['_DRNKWK3'] = df['_DRNKWK3'] / 100

# For smoking duration, negative values are likely data errors
df['_LCSYQTS'] = df['_LCSYQTS'].where(df['_LCSYQTS'] >= 0, other=pd.NA)

for col in ['_DRNKWK3', '_LCSYSMK', '_LCSYQTS']:
    df[col] = df[col].round(0).astype('Int64')

In [58]:
for col in df.columns:
    print(f"{col}: {df[col].unique()}")

_STATE: [ 1.  2.  4.  5.  6.  8.  9. 10. 11. 12. 13. 15. 16. 17. 18. 19. 20. 21.
 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35. 36. 37. 38. 39.
 40. 41. 42. 44. 45. 46. 48. 49. 50. 51. 53. 54. 55. 56. 66. 72. 78.]
GENHLTH: [ 3.  1.  2.  4.  5. nan]
PHYSHLTH: [ 2.  0. 30.  7.  5. 14.  1. nan 25. 20.  6.  3.  4. 15. 10.  8. 27. 12.
 29. 28. 21.  9. 19. 16. 23. 18. 17. 26. 24. 11. 22. 13.]
MENTHLTH: [ 0. 15.  1. nan 30.  2.  8. 10.  7.  6.  5.  4.  9. 25. 20.  3. 29. 11.
 12. 14. 26. 17. 23. 21. 28. 18. 22. 13. 19. 16. 27. 24.]
PRIMINS2: [ 3.  1.  5.  7. nan  9.  2. 10.  0.  4.  6.  8.]
PERSDOC3: [ 2.  1.  3. nan]
LASTDEN4: [ 1.  4.  2.  3. nan  0.]
RMVTETH4: [ 1.  2.  0.  3. nan]
CVDINFR4: [ 2.  1. nan]
CVDSTRK3: [0 1]
CHCOCNC1: [ 2.  1. nan]
CHCCOPD3: [ 2.  1. nan]
ADDEPEV3: [ 2.  1. nan]
CHCKDNY2: [ 2.  1. nan]
HAVARTH4: [ 1.  2. nan]
DIABETE4: [ 3.  1.  4.  2. nan]
DIABAGE4: [nan 44. 58. 33. 50. 55. 70. 62. 38. 47. 45. 35. 53. 59. 73. 32. 57. 52.
 60. 20. 65. 68. 51. 30. 75. 40. 72. 61. 76. 78. 28. 42. 29. 69. 67. 56.
 49. 80. 34. 54. 36. 63. 77. 25. 66. 94. 48. 43. 16. 41. 64. 74. 83. 39.
 71. 26. 21. 18. 37. 24. 22. 31. 27. 46.  9. 15. 19.  5. 82. 10. 23. 17.
  3. 13. 79.  7. 12. 11.  1.  4. 85.  6. 14. 86.  8. 90. 87. 84. 81. 92.
  2. 95. 88. 89. 91. 93. 97.]
MARITAL: [ 3.  1.  6.  5.  2. nan  4.]
EDUCA: [ 4.  6.  5.  3.  2. nan  1.]
VETERAN3: [ 2.  1. nan]
EMPLOY1: [ 7.  1.  8.  5. nan  2.  6.  3.  9.  4.]
INCOME3: [nan 11.  6.  3.  9.  5.  7.  8.  2. 10.  4.  1.]
PREGNANT: [nan  2.  1.]
DEAF: [ 2.  1. nan]
BLIND: [ 2.  1. nan]
DECIDE: [ 2.  1. nan]
DIFFWALK: [ 2.  1. nan]
DIFFDRES: [ 2.  1. nan]
DIFFALON: [ 2.  1. nan]
HADHYST2: [ 1. nan  2.]
ECIGNOW3: [ 1.  4. nan  3.  2.]
LCSFIRST: [nan 25. 14. 10. 22. 18. 11. 20. 17. 15. 32. 13. 16.  9. 12. 28. 19. 30.
 24. 34. 27. 21. 38. 23. 35. 40. 29. 33. 26.  8. 37.  4. 42. 31. 43.  2.
  7. 49.  6. 50. 44. 51. 52. 55.  3. 36.  5. 60. 41. 45. 69. 48. 46. 47.
 58. 39. 63. 53. 78. 70. 65. 61.  1. 77. 54. 62. 59. 56. 76. 64. 57. 75.
 79. 80. 71. 66. 68. 67. 72. 99. 81.]
FLUSHOT7: [ 1.  2. nan]
PNEUVAC4: [ 2.  1. nan]
PDIABTS1: [nan  1.  2.  0.  5.  6.  4.  3.]
PREDIAB2: [nan  1.  3.  2.]
DIABTYPE: [nan  2.  1.]
INSULIN1: [nan  2.  1.]
EYEEXAM1: [nan  3.  1.  2.  4.]
DIABEYE1: [nan  1.  2.  3.  4.  0.]
DIABEDU1: [nan  0.  1.  6.  5.  2.  3.  4.]
FEETSORE: [nan  2.  1.]
CNCRDIFF: [nan  1.  3.  2.]
CNCRAGE: [nan 75. 80. 30. 74. 60. 82. 76. 55. 50. 65. 70. 56. 62. 69. 61. 33. 40.
 58. 52. 49. 72. 86. 71. 35. 79. 36. 68. 48. 85. 77. 46. 78. 84. 67. 34.
 63. 43. 66. 83. 59. 41. 51. 64. 45. 73. 47. 88. 42. 38. 53. 17. 90. 31.
 24. 54. 28. 19. 39. 23. 57. 25. 37. 44. 12. 29. 18. 27. 26. 21.  2. 11.
 20. 32. 22. 16.  1. 81. 87. 10. 15.  7.  6. 92. 13. 14.  8.  9. 89.  5.
  4.  3. 94. 93. 91. 95.]
CNCRTYP2: [nan 27. 22. 20. 21. 14.  5. 30. 16. 10. 15. 23. 28.  7.  8.  6.  1. 25.
  3.  4. 26. 12. 29. 19.  2. 18. 13. 17.  9. 11. 24.]
CSRVTRT3: [nan  2.  5.  1.  4.  3.]
CSRVPAIN: [nan  1.  2.]
CIMEMLO1: [ 2.  1. nan]
CDWORRY: [nan  2.  1.]
CDDISCU1: [nan  1.  2.]
CDHOUS1: [nan  2.  1.]
CDSOCIA1: [nan  1.  2.]
ACEDEPRS: [nan  2.  1.]
ACEDRINK: [nan  2.  1.]
ACEDRUGS: [nan  2.  1.]
ACEPRISN: [nan  2.  1.]
ACEDIVRC: [nan  2.  1.  3.]
ACEPUNCH: [nan  1.  3.  2.]
ACEHURT1: [nan  1.  3.  2.]
ACESWEAR: [nan  1.  3.  2.]
ACETOUCH: [nan  1.  3.  2.]
ACETTHEM: [nan  1.  3.  2.]
ACEHVSEX: [nan  1.  3.  2.]
ACEADSAF: [nan  5.  4.  1.  3.  2.]
ACEADNED: [nan  5.  3.  4.  2.  1.]
LSATISFY: [ 1.  2.  3. nan  4.]
EMTSUPRT: [ 1.  2.  4.  5.  3. nan]
SDLONELY: [ 5.  1.  2.  3.  4. nan]
SDHEMPLY: [ 2. nan  1.]
HOWSAFE1: [ 1.  2. nan  4.  3.]
MARIJAN1: [nan  0. 30. 25.  1. 20.  5. 15.  3. 27.  2. 26. 29. 10.  8.  4.  7.  6.
 28. 16. 18. 12.  9. 14. 23. 21. 13. 24. 11. 22. 17. 19.]
SSBSUGR2: [ nan 302.   0. 103. 201. 101. 301. 102. 105. 303. 104. 203. 304. 310.
 305. 202. 223. 107. 204. 315. 191. 205. 308. 312. 224. 330. 120. 207.
 106. 306. 206. 230. 112. 325. 130. 307. 320. 360. 110. 314. 250. 311.
 399. 108. 324. 196. 221. 131. 199. 309. 212. 316. 115. 215. 328. 121.
 333. 210. 150. 299. 313. 329. 327. 321. 317. 220. 208. 233. 318. 124.
 323. 214. 129. 109. 118. 116. 326. 170. 322. 340. 336. 391. 123. 240.
 355. 122. 125. 209. 111. 113. 382. 335. 346. 222. 114. 292. 133. 249.
 390. 350. 395. 388. 331. 345. 225. 347. 141. 385. 117. 291. 198.]
SSBFRUT3: [ nan   0. 301. 201. 101. 302. 102. 103. 310. 304. 120. 303. 202. 203.
 315. 205. 305. 330. 112. 106. 105. 204. 107. 104. 320. 312. 131. 114.
 309. 130. 307. 350. 314. 306. 325. 318. 110. 215. 206. 316. 323. 308.
 207. 210. 321. 199. 115. 399. 109. 208. 317. 214. 108. 150. 327. 324.
 335. 360. 328. 340. 322. 211. 329. 225. 230. 128. 125. 221. 153. 242.
 212. 124. 313. 338. 220. 122. 113. 326. 299. 311. 331. 291. 222. 209.
 364. 118. 260. 224. 140. 217. 388. 116. 228. 390. 213.]
SOMALE: [nan  2.  3.  1.  4.]
SOFEMALE: [ 2. nan  1.  3.  4.]
_URBSTAT: [ 1.  2. nan]
_TOTINDA: [ 1.  2. nan]
_MICHD: [ 2.  1. nan]
_ASTHMS1: [ 3.  2.  1. nan]
_RACE: [ 1.  7.  2.  4.  8. nan  6.  3.  5.]
_SEX: [2. 1.]
_AGE80: [78. 80. 59. 47. 54. 71. 68. 70. 72. 75. 67. 77. 63. 76. 74. 62. 79. 60.
 69. 66. 56. 73. 65. 61. 21. 64. 44. 49. 45. 50. 58. 55. 51. 43. 52. 57.
 48. 53. 42. 37. 25. 39. 35. 41. 27. 20. 24. 29. 26. 19. 46. 36. 30. 33.
 28. 23. 31. 34. 32. 40. 38. 18. 22.]
_BMI5: [22.49 25.83 22.53 ... 42.46 45.95 40.65]
_SMOKER3: [ 4.  3.  1. nan  2.]
LCSLAST_: [nan 27. 10. 72. 68. 30. 38. 50. 45. 55. 32. 46. 65. 22. 60. 25. 16. 57.
 26. 66. 24. 40. 34. 21. 58. 79. 36. 80. 63. 33. 23. 20. 29. 51. 42. 35.
 47. 44. 70. 37. 18. 75. 48. 43. 69. 73. 81. 62. 71. 28. 52. 12. 64. 53.
 61. 49. 39. 56. 19. 59. 54. 31. 67. 17. 41. 15. 77. 74. 78. 76. 14. 13.
 11.  4.  9.  2.  6.  3.  7.  5.  1.  8.]
LCSNUMC_: [ nan  20.  15.   7.   4.   5.  12.  10.  40.  30.   2.   3.  60.  16.
   1.   6.  35.  50.  18.  25.   8.  11.  13.   9.  70.  29.  14.  24.
  23.  72. 125.  28. 100.  17.  80.  45.  75. 140. 115.  27.  19.  21.
 300.  22. 200. 110. 201.  32. 143. 106. 107.  46. 150. 103.  90.  77.
  48.  49.  26.  55. 120.  88.  65. 104.  36. 105. 118. 102.  31. 101.
 210. 202. 130.  33. 205. 108. 113. 175.  43.  74. 203.  83.  82.  67.
  84.  39. 290.  47.  34. 152.  42.  56. 230.  85. 260. 135. 204. 209.
  68. 180. 155. 153.  52. 156.  73.  38.  54.  63.  53.  58. 225.  71.
  62.  57.  44.  99.  37.  76.  78. 160. 215.  66.  64. 190. 490.  51.]
_LCSYSMK: <IntegerArray>
[<NA>,    2,   45,    0,   50,   57,   10,   18,   30,   12,   42,   16,   47,
   28,   31,   32,    7,    1,    4,   33,   56,   39,   11,   48,   60,   41,
    6,   44,   40,   21,   34,   22,    8,   43,   24,   61,   46,   36,   58,
   29,   20,    3,   64,   54,    5,   49,   26,   63,   53,   17,   55,   14,
   27,   52,   23,   38,   37,   35,   62,   25,   65,   66,   70,   51,   19,
    9,   13,   15,   79,   68,   67,   59,   82,   77,   76,   71,   69,   72,
   73,   75,   74,   81,   94,   78,   86,   88,   90,   85,   89,   83]
Length: 90, dtype: Int64
_LCSYQTS: <IntegerArray>
[<NA>,   53,   80,    0,    3,   51,   37,   26,   29,    5,   48,   27,   42,
   10,   44,   15,   36,   45,   49,   20,   11,   40,   60,   30,   25,   38,
   24,   32,   50,   35,   14,    2,    6,   41,   22,   46,   52,   59,   55,
   16,   39,   61,   34,    9,   17,   67,   31,   23,   43,   21,   47,   33,
   13,   28,   19,    1,   58,   62,   54,   63,    4,   56,    7,   12,    8,
   18,   57,   66,   65,   69,   68,   70,   71,   64,   74,   73,   76,   78,
   83,   77,   75,   72,   81,   79]
Length: 84, dtype: Int64
_LCSELIG: [ 2.  1. nan]
_LCSCTSN: [nan  4.  3.  2.  1.]
_DRNKWK3: <IntegerArray>
[   0,   14,    4, <NA>,    1,    9,    6,   10,    8,   28,
 ...
  128,  525,   68,  158,  160,  180,  142,  152,  122,  262]
Length: 159, dtype: Int64

In [59]:
base_datasets = build_feature_datasets(df, target_col)

# Two variants: with and without uncertain features
uncertain_set = set(uncertain_features)

def drop_uncertain(ds):
    """Return dataset with uncertain features removed."""
    return ds.drop(columns=[c for c in uncertain_set if c in ds.columns])

dataset_definitions = {
    'with_uncertain': base_datasets,
    'without_uncertain': {name: drop_uncertain(ds) for name, ds in base_datasets.items()},
}

# Register datasets
datasets = {}

if any(DATASETS_DIR.iterdir()):
    print("Datasets folder is not empty, skipping dataset creation.")
    for uncertainty_variant, feature_sets in dataset_definitions.items():
        for feat_name in feature_sets:
            dataset_id = f"{feat_name}_{uncertainty_variant}"
            datasets[dataset_id] = {
                'df': load_dataset(dataset_id),
                'feature_set': feat_name,
                'uncertainty': uncertainty_variant,
            }
            print(f"Loaded dataset: {dataset_id}")
else:
    for uncertainty_variant, feature_sets in dataset_definitions.items():
        for feat_name, ds in feature_sets.items():
            dataset_id = f"{feat_name}_{uncertainty_variant}"
            datasets[dataset_id] = {
                'df': ds,
                'feature_set': feat_name,
                'uncertainty': uncertainty_variant,
            }
            register_dataset(dataset_id, ds, label=dataset_id.replace('_', ' ').title())
            print(f"Registered dataset: {dataset_id}  features={ds.shape[1] - 1}")

Datasets folder is not empty, skipping dataset creation.
Loaded dataset: lifestyle_with_uncertain
Loaded dataset: clinical_with_uncertain
Loaded dataset: combined_with_uncertain
Loaded dataset: lifestyle_without_uncertain
Loaded dataset: clinical_without_uncertain
Loaded dataset: combined_without_uncertain

# Train selected final models

This notebook trains the actual model set used by the application. The selected configurations come from `Model Stats Overview.xlsx`: for each algorithm, one configuration has the best overall balance of stroke-risk statistics and one prioritizes a very low false-negative count.

All final models use the weighted data-balancing method and are trained for clinical, lifestyle, and combined feature sets with and without uncertain features. Model files are stored in `ai_module/models`.

In [60]:
pd.DataFrame([
    {
        "algorithm": config["algorithm"],
        "profile": config["profile"],
        "threshold": config["classificationThreshold"],
        "source_false_negatives": config["sourceMetrics"]["falseNegatives"],
        "source_false_positives": config["sourceMetrics"].get("falsePositives"),
        "hyperparameters": config["hyperparameters"],
    }
    for config in FINAL_MODEL_CONFIGS
])

,algorithm,profile,threshold,source_false_negatives,source_false_positives,hyperparameters
0,random_forest,best_balance,0.5,962,23456,"{'max_depth': 9, 'min_samples_leaf': 4, 'n_est..."
1,random_forest,low_false_negative,0.4,330,42420,"{'max_depth': 3, 'min_samples_leaf': 1, 'n_est..."
2,lightgbm,best_balance,0.5,920,23787,"{'learning_rate': 0.05, 'max_depth': 10, 'n_es..."
3,lightgbm,low_false_negative,0.4,553,32261,"{'learning_rate': 0.05, 'max_depth': 10, 'n_es..."
4,xgboost,best_balance,0.5,906,23562,"{'learning_rate': 0.1, 'max_depth': 3, 'n_esti..."
5,xgboost,low_false_negative,0.4,519,33902,"{'learning_rate': 0.05, 'max_depth': 3, 'n_est..."

In [61]:
FORCE_RETRAIN = False
USE_GPU = True

DATASET_IDS = FINAL_MODEL_DATASET_IDS
CONFIGS = FINAL_MODEL_CONFIGS

print(f"Datasets: {len(DATASET_IDS)}")
print(f"Selected configs: {len(CONFIGS)}")
print(f"Final models to process: {len(DATASET_IDS) * len(CONFIGS)}")

Datasets: 6
Selected configs: 6
Final models to process: 36

In [62]:
result = train_or_reuse_final_models(
    dataset_ids=DATASET_IDS,
    configs=CONFIGS,
    force_retrain=FORCE_RETRAIN,
    use_gpu=USE_GPU,
)

result["total"], result["trained"], result["reused"], result["modelOutputDir"]

All 36 final models already exist in C:\CP Project\Lifestyle-and-Clinical-Factors-in-Stroke-Risk-Prediction\ai_module\models. Skipping training.

(36,
 0,
 36,
 'C:\\CP Project\\Lifestyle-and-Clinical-Factors-in-Stroke-Risk-Prediction\\ai_module\\models')

In [63]:
pd.DataFrame([
    {
        "model_id": model["modelId"],
        "algorithm": model["algorithm"],
        "dataset": model["datasetId"],
        "profile": model["modelId"].split("__final_", 1)[-1],
        "threshold": model["classificationThreshold"],
        "auc": model["metrics"].get("auc"),
        "f1": model["metrics"].get("f1"),
        "precision": model["metrics"].get("precision"),
        "recall": model["metrics"].get("recall"),
        "false_negatives": model["confusionMatrix"].get("fn"),
        "false_positives": model["confusionMatrix"].get("fp"),
        "reused": model["reusedExistingModel"],
    }
    for model in result["models"]
])

,model_id,algorithm,dataset,profile,threshold,auc,f1,precision,recall,false_negatives,false_positives,reused
0,random_forest_weighted_clinical_with_uncertain...,random_forest,clinical_with_uncertain,best_balance,0.5,0.826627,0.203515,0.117139,0.774927,930,24133,True
1,random_forest_weighted_clinical_with_uncertain...,random_forest,clinical_with_uncertain,low_false_negative,0.4,0.819108,0.152489,0.083149,0.918199,338,41835,True
2,lightgbm_weighted_clinical_with_uncertain__fin...,lightgbm,clinical_with_uncertain,best_balance,0.5,0.830509,0.205400,0.118323,0.777832,918,23949,True
3,lightgbm_weighted_clinical_with_uncertain__fin...,lightgbm,clinical_with_uncertain,low_false_negative,0.4,0.830110,0.179398,0.100042,0.867619,547,32250,True
4,xgboost_weighted_clinical_with_uncertain__fina...,xgboost,clinical_with_uncertain,best_balance,0.5,0.831015,0.207076,0.119425,0.778316,916,23713,True
5,xgboost_weighted_clinical_with_uncertain__fina...,xgboost,clinical_with_uncertain,low_false_negative,0.4,0.826775,0.173282,0.096191,0.872701,526,33882,True
6,random_forest_weighted_clinical_without_uncert...,random_forest,clinical_without_uncertain,best_balance,0.5,0.809289,0.188849,0.107384,0.782430,899,26874,True
7,random_forest_weighted_clinical_without_uncert...,random_forest,clinical_without_uncertain,low_false_negative,0.4,0.799979,0.144863,0.078640,0.917473,341,44416,True
8,lightgbm_weighted_clinical_without_uncertain__...,lightgbm,clinical_without_uncertain,best_balance,0.5,0.814114,0.193348,0.110264,0.784366,891,26152,True
9,lightgbm_weighted_clinical_without_uncertain__...,lightgbm,clinical_without_uncertain,low_false_negative,0.4,0.813610,0.170943,0.094774,0.870765,534,34366,True
10,xgboost_weighted_clinical_without_uncertain__f...,xgboost,clinical_without_uncertain,best_balance,0.5,0.814626,0.193947,0.110525,0.790900,864,26300,True
11,xgboost_weighted_clinical_without_uncertain__f...,xgboost,clinical_without_uncertain,low_false_negative,0.4,0.809474,0.165526,0.091345,0.880929,492,36209,True
12,random_forest_weighted_lifestyle_with_uncertai...,random_forest,lifestyle_with_uncertain,best_balance,0.5,0.797652,0.182935,0.103648,0.778316,916,27812,True
13,random_forest_weighted_lifestyle_with_uncertai...,random_forest,lifestyle_with_uncertain,low_false_negative,0.4,0.786579,0.140948,0.076409,0.907309,383,45316,True
14,lightgbm_weighted_lifestyle_with_uncertain__fi...,lightgbm,lifestyle_with_uncertain,best_balance,0.5,0.803347,0.187422,0.106547,0.777832,918,26951,True
15,lightgbm_weighted_lifestyle_with_uncertain__fi...,lightgbm,lifestyle_with_uncertain,low_false_negative,0.4,0.803088,0.164226,0.090747,0.863020,566,35730,True
16,xgboost_weighted_lifestyle_with_uncertain__fin...,xgboost,lifestyle_with_uncertain,best_balance,0.5,0.803649,0.187018,0.106228,0.780978,905,27151,True
17,xgboost_weighted_lifestyle_with_uncertain__fin...,xgboost,lifestyle_with_uncertain,low_false_negative,0.4,0.798900,0.160373,0.088322,0.870523,535,37129,True
18,random_forest_weighted_lifestyle_without_uncer...,random_forest,lifestyle_without_uncertain,best_balance,0.5,0.797810,0.182471,0.103410,0.774927,930,27762,True
19,random_forest_weighted_lifestyle_without_uncer...,random_forest,lifestyle_without_uncertain,low_false_negative,0.4,0.787036,0.141544,0.076756,0.907793,381,45118,True
20,lightgbm_weighted_lifestyle_without_uncertain_...,lightgbm,lifestyle_without_uncertain,best_balance,0.5,0.803076,0.187526,0.106614,0.777832,918,26932,True
21,lightgbm_weighted_lifestyle_without_uncertain_...,lightgbm,lifestyle_without_uncertain,low_false_negative,0.4,0.802499,0.163920,0.090560,0.863020,566,35811,True
22,xgboost_weighted_lifestyle_without_uncertain__...,xgboost,lifestyle_without_uncertain,best_balance,0.5,0.804165,0.186431,0.105872,0.779768,910,27211,True
23,xgboost_weighted_lifestyle_without_uncertain__...,xgboost,lifestyle_without_uncertain,low_false_negative,0.4,0.798979,0.160743,0.088534,0.871733,530,37083,True
24,random_forest_weighted_combined_with_uncertain...,random_forest,combined_with_uncertain,best_balance,0.5,0.826894,0.206125,0.119057,0.767183,962,23456,True
25,random_forest_weighted_combined_with_uncertain...,random_forest,combined_with_uncertain,low_false_negative,0.4,0.820347,0.151011,0.082255,0.920136,330,42420,True
26,lightgbm_weighted_combined_with_uncertain__fin...,lightgbm,combined_with_uncertain,best_balance,0.5,0.831416,0.206354,0.118967,0.777348,920,23787,True
27,lightgbm_weighted_combined_with_uncertain__fin...,lightgbm,combined_with_uncertain,low_false_negative,0.4,0.830835,0.179075,0.099860,0.866167,553,32261,True
28,xgboost_weighted_combined_with_uncertain__fina...,xgboost,combined_with_uncertain,best_balance,0.5,0.831754,0.208668,0.120427,0.780736,906,23562,True
29,xgboost_weighted_combined_with_uncertain__fina...,xgboost,combined_with_uncertain,low_false_negative,0.4,0.826991,0.173506,0.096308,0.874395,519,33902,True
30,random_forest_weighted_combined_without_uncert...,random_forest,combined_without_uncertain,best_balance,0.5,0.809484,0.189387,0.107672,0.785576,886,26901,True
31,random_forest_weighted_combined_without_uncert...,random_forest,combined_without_uncertain,low_false_negative,0.4,0.801336,0.143278,0.077660,0.924008,314,45345,True
32,lightgbm_weighted_combined_without_uncertain__...,lightgbm,combined_without_uncertain,best_balance,0.5,0.815081,0.193560,0.110436,0.782672,898,26050,True
33,lightgbm_weighted_combined_without_uncertain__...,lightgbm,combined_without_uncertain,low_false_negative,0.4,0.814389,0.171729,0.095241,0.872217,528,34237,True
34,xgboost_weighted_combined_without_uncertain__f...,xgboost,combined_without_uncertain,best_balance,0.5,0.815629,0.193256,0.110204,0.784366,891,26168,True
35,xgboost_weighted_combined_without_uncertain__f...,xgboost,combined_without_uncertain,low_false_negative,0.4,0.810022,0.166385,0.091868,0.880929,492,35982,True